config/routes.rb
Rails.application.routes.draw do
  resources :blogposts do
    resources :comments
  end
  resources :forecasts do
    resources :rainfalls
  end
  resources :profiles
  devise_for :users
  root to: "home#index"
  get 'comments/index', :action=>"index", :controller=>"comments"
  get 'comments/show', :action=>'show', :controller=>'comments'
  get 'comments/new', :action=>'new', :controller=>'comments'
  get 'comments/edit', :action=>'edit', :controller=>'comments'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  #get 'home/index', :controller=>'weekdays', :action=>'day'
  get 'home/index'
  get 'rainfalls/index', :action=>'index', :controller=>'rainfalls'
  #post 'rainfalls/create', :action=>'create', :controller=>'rainfalls'
  get 'rainfalls/show', :action=>'show', :controller=>'rainfalls'
  #get 'rainfalls/show/:id/:forecast_id', :action=>'show', :controller=>'rainfalls'
  get 'rainfalls/new', :action=>'new', :controller=>'rainfalls'
  get 'rainfalls/edit', :action=>'edit', :controller=>'rainfalls'
  #post 'forecasts/:forecast_id/rainfalls/:id', :action=>'create', :controller=>'rainfalls' => as 
  #post '/checkprofanity', :controller=>'comments', :action=>'isprofanity'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #get '/day', :controller=>'weekdays', :action=>'day'
  #post '/day', :controller=>'weekdays', :action=>'day'
  get 'blogpostsearch', to: "blogposts#search"
  get 'forecastsearch', to: "forecasts#search"

end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
    has_many :comment, :dependent => :delete_all
    validates :title , presence: true, length: {minimum: 10}
    validates :category , presence: true, length: {minimum: 10}
    validates :author , presence: true, length: {minimum: 4}
    validates :image_url , presence: true
end

app/controllers/blogposts_controller.rb
require 'blog_notification/notification'
require 'blog_notification/displayer'
require 'blog_notification/subject'
require 'day_of_week/current_day'
require 'weather_rss_reader/weather_rss'

class BlogpostsController < ApplicationController
  #before_action :authenticate_user!
  before_action :ensure_admin, :only => [:edit, :destroy]
  before_action :set_blogpost, only: %i[ show edit update destroy ]



  def ensure_admin
    unless current_user && current_user.admin?
      render :text => "Access Error Message", :status => :unauthorized
    end
  end

  # GET /blogposts or /blogposts.json
  def index
    @blogposts = Blogpost.all
    #used for current day and date.
    #@WeatherRss = WeatherRSS.new()
    @weather_rss = WeatherRSS.weather_rss
  end

  def search
    @blogposts = Blogpost.where("title LIKE ?", "%" + params[:q] + "%")
  end

  # GET /blogposts/1 or /blogposts/1.json
  def show
  end

  # GET /blogposts/new
  def new
    @blogpost = Blogpost.new
  end

  # GET /blogposts/1/edit
  def edit
  end

  # POST /blogposts or /blogposts.json
  def create
    
    @blogpost = Blogpost.new(blogpost_params)
    #@blogpost.add_observer(self)

    #puts "YERRRRRR" + @blogpost.title
    
    #@notification = BlogNotification.new(@blogpost.title, @blogpost.category, Time.now)
    #@displayer = Displayer.new(@notification)    

    
    #@notification.update_date()
    #render partial: "shared/newblog"


    respond_to do |format|
      if @blogpost.save
        #@notification.update_date()
        format.html { redirect_to blogposts_path , notice: "Blogpost was successfully created.", locals: {:title => @blogpost.title, :category => @blogpost.category, :date => @date}}
        #format.json { render :show, status: :created, location: @blogpost }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end
  helper_method :notification

  # PATCH/PUT /blogposts/1 or /blogposts/1.json
  def update
    respond_to do |format|
      if @blogpost.update(blogpost_params)
        format.html { redirect_to @blogpost, notice: "Blogpost was successfully updated." }
        format.json { render :show, status: :ok, location: @blogpost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogposts/1 or /blogposts/1.json
  def destroy
    @blogpost.destroy
    puts "Should be destroyed"
    respond_to do |format|
      format.html { redirect_to blogposts_url, notice: "Blogpost was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogpost
      @blogpost = Blogpost.find(params[:id])
      puts @blogpost.id
    end

    # Only allow a list of trusted parameters through.
    def blogpost_params
      params.require(:blogpost).permit(:title, :category, :author, :image_url, :content)
    end
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/views/blogposts/_blogpost_record.erb
<h1>Blogposts</h1>
        <% @blogposts.each do |blogpost| %>
          <div class="container bg-light border mb-4 justify-content-md-center">
            <br>
            <div class="d-flex flex-row">
              <h3><%= blogpost.title %></h3>
            </div>
            <div class="d-flex flex-row mb-2">
              <div class="p-2">Category: <b><%= blogpost.category %></b></div>
              <div class="p-2">Author: <b><%= blogpost.author %></b></div>
              <div class="p-2"><i>Date Created: <%= blogpost.created_at %></i></div>
            </div>
            <div class="d-flex flex-row mb-2">
              <div class="d-flex flex-col">
                <div class="p-2"><%= image_tag (blogpost.image_url), size: "260x180"%></div>
              </div>
              <div class="d-flex flex-col">
                <div class="p-2"><p><%= blogpost.content %></p></div>
              </div>
            </div>
            <div>
            <% if current_user.present? %>            
              <% if current_user.admin? %>
                <a href="<%= blogpost_comments_path(blogpost, @comment) %>">Comments Section</a>
              <% end %>
            <% end %>
              <% @comments = blogpost.comment %>
              <p class="fs-4 p-2">Comments Section</p>
              <% if current_user.present? %>
                <%= link_to 'New Comment', new_blogpost_comment_path(blogpost) %>
              <% end %>
              <% for comment in @comments %>
                <br>
                <div class="col-md-12 offset-md-3 pd-5">
                  <div class="col col-lg-2">
                  </div>
                  <div class="col col-lg-6">
                    <div class=" w-100 p-2 row border bg-light border-secondary rounded-pill border-1 border-bottom-2 border-top-0 border-start-0 border-end-0">
                      <p class="fw-light">Comment:</p> <p class="fs-6"><%= comment.message %></p>
                    </div>
                  </div>
                  <div class="col col-lg-2">
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>

app/views/blogposts/_form.html.erb
<%= form_with(model: blogpost) do |form| %>
  <% if blogpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blogpost.errors.count, "error") %> prohibited this blogpost from being saved:</h2>

      <ul>
        <% blogpost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogposts/_notification.html.erb
<span>Variable has value <%= latest_blogpost %>, while the other variable has value <%= other_variable %>.</span>

<%= latest_blogpost.author%>

app/views/blogposts/admin.html.erb
<table>
<thead>
    <tr>
    <th>Title</th>
    <th>Category</th>
    <th>Content</th>
    <th>Author</th>
    <th>Image url</th>
    <th colspan="3"></th>
    </tr>
</thead>

<tbody>
    <% @blogposts.each do |blogpost| %>
    <tr>
        <td><%= blogpost.title %></td>
        <td><%= blogpost.category %></td>
        <td><%= blogpost.content %></td>
        <td><%= blogpost.author %></td>
        <td><%= blogpost.image_url %></td>
        <td><%= link_to 'Show', blogpost %></td>
        <td><%= link_to 'Edit', edit_blogpost_path(blogpost) %></td>
        <td><%= link_to 'Destroy', blogpost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
</tbody>
</table>

app/views/blogposts/edit.html.erb
<h1>Editing Blogpost</h1>

<%= render 'form', blogpost: @blogpost %>

<%= link_to 'Show', @blogpost %> |
<%= link_to 'Back', blogposts_path %>

app/views/blogposts/index.html.erb
<head>
  <%= render partial: "shared/navbar" %>
  <%= render partial: "shared/blogpost_search" %>
</head>

<p id="notice"><%= notice %></p>
<%= puts "Weather Report #{@notification} was published on #{@notification}\n" %>

<body>
  <div class="container-fluid">
    <div class="row justify-content-md-center">
      <div class="col col-lg-2 justify-content-center">
        <%= render partial: "shared/weather_rss" %>
      </div>
      <div class="col col-lg-8">
        <%= render partial: "blogposts/blogpost_record" %>
      </div>

      <div class="col col-lg-2 p-auto justify-content-center">
        <a class="twitter-timeline" data-lang="en" data-height="1080" href="https://twitter.com/MetEireann?ref_src=twsrc%5Etfw">Tweets by MetEireann</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>
    </div>
  </div>
  
  <% if current_user.present? %>
    <% if current_user.admin? %>
      <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
        Admin Menu
      </button>
      <%= link_to 'Create New Blogpost', new_blogpost_path, class: "btn btn-success fw-normal text-white" %>
      <div class="collapse" id="collapseExample">
        <div class="card card-body">
          <table>
            <thead>
              <tr>
                <th>Title</th>
                <th>Category</th>
                <th>Content</th>
                <th>Author</th>
                <th>Image url</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @blogposts.each do |blogpost| %>
                <tr>
                  <td><%= blogpost.title %></td>
                  <td><%= blogpost.category %></td>
                  <td><%= blogpost.content %></td>
                  <td><%= blogpost.author %></td>
                  <td><%= blogpost.image_url %></td>
                  <td><%= link_to 'Show', blogpost %></td>
                  <td><%= link_to 'Edit', edit_blogpost_path(blogpost) %></td>
                  <td><%= button_to 'Destroy', blogpost, method: :delete, dependent: :destroy, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>
  <% end %>
</body>
<br>
<footer>
  <%= render partial: "shared/footer" %>
</footer>

app/views/blogposts/new.html.erb
<%= render partial: "shared/navbar" %>
<div class="row">
    <div class="col text-center justify-content-center pt-5">
        <h1>New Blogpost</h1>
        <%= render 'form', blogpost: @blogpost %>
        <%= link_to 'Back', blogposts_path %>
    </div>
</div>

app/views/blogposts/search.html.erb
<head>
  <%= render partial: "shared/navbar" %>
</head>

<h1> Searched Blogpost Results</h1>

<%= render partial: "blogposts/blogpost_record" %>

<% @date %>

<% if @blogposts.blank? %>
    <div class="row justify-content-center">
        <div class="col col-lg-12 justify-content-center text-center">
            <h2 class="text-danger pb-5 pt-5">No records for searched blogpost</h2>  
        </div>
    </div>
           
<% end %>

<footer>
  <%= render partial: "shared/footer" %>
</footer>

app/views/blogposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blogpost.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @blogpost.category %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blogpost.content %>
</p>

<p>
  <strong>Author:</strong>
  <%= @blogpost.author %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @blogpost.image_url %>
</p>

<!-- Display the reviews of a movie -->
<h2>Comments</h2>
<% @blogpost.comment.each do |comment| %>
<p>
<b>Comment details:</b>
<%= comment.message %>
</p>
<% end %>
<%= link_to 'Edit Blog', edit_blogpost_path(@blogpost) %> |
<%= link_to 'Back', blogposts_path %>
<%= link_to 'Show Comments', blogpost_comments_path(@blogpost) %>


