config/routes.rb
Rails.application.routes.draw do
  resources :blogposts do
    resources :comments
  end
  resources :forecasts do
    resources :rainfalls
  end
  resources :profiles
  devise_for :users
  root to: "home#index"
  get 'comments/index', :action=>"index", :controller=>"comments"
  get 'comments/show', :action=>'show', :controller=>'comments'
  get 'comments/new', :action=>'new', :controller=>'comments'
  get 'comments/edit', :action=>'edit', :controller=>'comments'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  #get 'home/index', :controller=>'weekdays', :action=>'day'
  get 'home/index'
  get 'rainfalls/index', :action=>'index', :controller=>'rainfalls'
  #post 'rainfalls/create', :action=>'create', :controller=>'rainfalls'
  get 'rainfalls/show', :action=>'show', :controller=>'rainfalls'
  #get 'rainfalls/show/:id/:forecast_id', :action=>'show', :controller=>'rainfalls'
  get 'rainfalls/new', :action=>'new', :controller=>'rainfalls'
  get 'rainfalls/edit', :action=>'edit', :controller=>'rainfalls'
  #post 'forecasts/:forecast_id/rainfalls/:id', :action=>'create', :controller=>'rainfalls' => as 
  #post '/checkprofanity', :controller=>'comments', :action=>'isprofanity'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #get '/day', :controller=>'weekdays', :action=>'day'
  #post '/day', :controller=>'weekdays', :action=>'day'
  get 'blogpostsearch', to: "blogposts#search"
  get 'forecastsearch', to: "forecasts#search"

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blogpost
  validates :message , presence: true, length: {minimum: 10}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    # For URL like /Blogposts/1/comments
    # Get the Blogpost with id=1
    @blogpost = Blogpost.find(params[:blogpost_id])
    # Access all comments for that Blogpost
    @comments = @blogpost.comment    
  end

  def show
    @blogpost = Blogpost.find(params[:blogpost_id])
    # For URL like /Blogposts/1/comments/2
    # Find an comment in Blogposts 1 that has id=2
    @comment = @blogpost.comment.find(params[:id])
  end

  def new
    @blogpost = Blogpost.find(params[:blogpost_id])
    # Associate an comment object with Blogpost 1
    @comment = @blogpost.comment.build
  end

  # POST /Blogposts/1/comments
  def create
    @blogpost = Blogpost.find(params[:blogpost_id])
    # For URL like /Blogposts/1/comments
    # Populate an comment associate with Blogpost 1 with form data
    # Blogpost will be associated with the comment
    # @comment = @blogpost.comments.build(params.require(:comment).permit!)
    @comment = @blogpost.comment.build(params.require(:comment).permit(:message))
    @comment.message = Checkprofanity.runcheck(@comment.message)
    if @comment.save
      # Save the comment successfully
      redirect_to blogposts_path(@blogpost)
      #redirect_to blogpost_comment_url(@blogpost, @comment)
      #redirect_to blogpost_url(@blogpost)
    else
      render :action => "new"
    end
  end
  

  def edit
    @blogpost = Blogpost.find(params[:blogpost_id])
    # For URL like /Blogposts/1/comments/2/edit
    # Get comment id=2 for Blogpost 1
    @comment = @blogpost.comment.find(params[:id])
  end

  def update
    @blogpost = Blogpost.find(params[:blogpost_id])
    @comment = Comment.find(params[:id])
    if @comment.update(params.require(:comment).permit(:message))
      # Save the comment successfully
      redirect_to blogpost_comment_url(@blogpost, @comment)
    else
      render :action => "edit"
    end
  end

  # DELETE /movies/1/reviews/2
  def destroy
    @blogpost = Blogpost.find(params[:blogpost_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to blogpost_comments_path}
      format.json { head :ok }
    end
  end

  # Added this manually
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:message)
  end

end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/comments/_form.html.erb
<%= form_for([@blogpost, @comment]) do |f| %>
<% if @comment.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@comment.errors.count, "error")%>
prohibited this comment from being saved:</h2>
<ul>
<% @comment.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>
<div class="field">
<p>
<%= f.label :Comment %><br />
<%= f.text_field :message %>
</p>
</div>
<div class="actions">
<%= f.submit %>
</div>
<% end %>

app/views/comments/edit.html.erb
<%= render partial: "shared/navbar" %>

<div class="row">
    <div class="col text-center justify-content-center pt-5">
        <h1>Editing Comment</h1>
        <%= render 'form' %>
        <%= link_to 'Show', blogpost_comment_path(@blogpost, @comment) %> |
        <%= link_to 'Back', blogpost_comments_path(@blogpost) %>
    </div>
</div>

app/views/comments/index.html.erb
<%= render partial: "shared/navbar" %>
<p id="notice"><%= notice %></p>

<h1>Comments for <%= @blogpost.title %></h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
    <% for comment in @comments %>
  </thead>

  <tbody>
    <% comment.message %>
      <tr>
        <td><%= comment.message %></td>
        <td><%= link_to 'Show', blogpost_comment_path(@blogpost, comment) %></td>
        <td><%= link_to 'Edit', edit_blogpost_comment_path(@blogpost, comment) %></td>
        <td><%= button_to 'Destroy', blogpost_comment_path(@blogpost, comment), :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
  </tbody>
  <% end %>
</table>

<br>

<%= link_to 'New Comment', new_blogpost_comment_path(@blogpost) %>
<%= link_to 'Back to Post', @blogpost %>

app/views/comments/new.html.erb
<%= render partial: "shared/navbar" %>

<div class="row">
    <div class="col text-center justify-content-center pt-5">
        <h1>New Comment</h1>
        <%= render 'form' %>
        <%= link_to 'Back', blogposts_path %>
    </div>
</div>

app/views/comments/show.html.erb
<%= render partial: "shared/navbar" %>
<div class="row">
    <div class="col text-center justify-content-center pt-5">
        <p id="notice"><%= notice %></p>
    
        <h1>Comments for <%= @blogpost.title %></h1>
        <p>
        <b>Comment details:</b>
        <%= @comment.message %>
        </p>
        <%= link_to 'Edit', edit_blogpost_comment_path(@blogpost, @comment) %> |
        <%= link_to 'Back', blogpost_comments_path(@blogpost) %>
    </div>
</div>