config/routes.rb
Rails.application.routes.draw do
  resources :blogposts do
    resources :comments
  end
  resources :forecasts do
    resources :rainfalls
  end
  resources :profiles
  devise_for :users
  root to: "home#index"
  get 'comments/index', :action=>"index", :controller=>"comments"
  get 'comments/show', :action=>'show', :controller=>'comments'
  get 'comments/new', :action=>'new', :controller=>'comments'
  get 'comments/edit', :action=>'edit', :controller=>'comments'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  #get 'home/index', :controller=>'weekdays', :action=>'day'
  get 'home/index'
  get 'rainfalls/index', :action=>'index', :controller=>'rainfalls'
  #post 'rainfalls/create', :action=>'create', :controller=>'rainfalls'
  get 'rainfalls/show', :action=>'show', :controller=>'rainfalls'
  #get 'rainfalls/show/:id/:forecast_id', :action=>'show', :controller=>'rainfalls'
  get 'rainfalls/new', :action=>'new', :controller=>'rainfalls'
  get 'rainfalls/edit', :action=>'edit', :controller=>'rainfalls'
  #post 'forecasts/:forecast_id/rainfalls/:id', :action=>'create', :controller=>'rainfalls' => as 
  #post '/checkprofanity', :controller=>'comments', :action=>'isprofanity'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #get '/day', :controller=>'weekdays', :action=>'day'
  #post '/day', :controller=>'weekdays', :action=>'day'
  get 'blogpostsearch', to: "blogposts#search"
  get 'forecastsearch', to: "forecasts#search"

end

app/models/rainfall.rb
class Rainfall < ApplicationRecord
  belongs_to :forecast
  validates :amount , presence: true, length: {minimum: 0, maximum: 5}, :numericality => { :greater_than_or_equal_to => 0 }
  validates :forecast_id , presence: true, length: {minimum: 0, maximum: 1}
end

app/controllers/rainfalls_controller.rb
class RainfallsController < ApplicationController
  before_action :ensure_admin, :only => [:index, :edit, :destroy]
  before_action :set_rainfall, only: %i[ show edit update destroy ]

  def ensure_admin
    unless current_user && current_user.admin?
      render :text => "Access Error Message", :status => :unauthorized
    end
  end

  #before_action :authenticate_user!
  # GET /movies/1/rainfalls
  def index
    # For URL like /movies/1/rainfalls
    # Get the movie with id=1
    @forecast = Forecast.find(params[:forecast_id])
    # Access all rainfalls for that movie
    @rainfalls = @forecast.rainfall
  end
    
  # GET /movies/1/rainfalls/2
  def show
    @forecast = Forecast.find(params[:forecast_id])
    # For URL like /movies/1/rainfalls/2
    # Find an review in movies 1 that has id=2
    @rainfall = @forecast.rainfall.find(params[:id])
  end
    
  # GET /movies/1/rainfalls/new
  def new
    @forecast = Forecast.find(params[:forecast_id])
    # Associate an review object with movie 1
    @rainfall = @forecast.rainfall.build
  end
    
  # POST /movies/1/rainfalls
  def create
    @forecast = Forecast.find(params[:forecast_id])
    # For URL like /movies/1/rainfalls
    # Populate an review associate with movie 1 with form data
    # Movie will be associated with the review
    # @rainfall = @forecast.rainfalls.build(params.require(:review).permit!)
    @rainfall = @forecast.rainfall.build(params.require(:rainfall).permit(:amount, :forecast_id))
    if @rainfall.save
    # Save the review successfully
    redirect_to forecast_rainfall_url(@forecast, @rainfall)
    else
    render :action => "new"
    end
  end
    
    # GET /movies/1/rainfalls/2/edit
  def edit
    @forecast = Forecast.find(params[:forecast_id])
    # For URL like /movies/1/rainfalls/2/edit
    # Get review id=2 for movie 1
    @rainfall = @forecast.rainfall.find(params[:id])
  end
    
    # PUT /movies/1/rainfalls/2
  def update
    @forecast = Forecast.find(params[:forecast_id])
    @rainfall = Rainfall.find(params[:id])
    if @rainfall.update(params.require(:rainfall).permit(:amount))
    # Save the review successfully
    redirect_to forecast_rainfall_url(@forecast, @rainfall)
    else
    render :action => "edit"
    end
  end
    
    # DELETE /movies/1/rainfalls/2
    def destroy
    @forecast = Forecast.find(params[:forecast_id])
    @rainfall = Rainfall.find(params[:id])
    @rainfall.destroy
    respond_to do |format|
    format.html { redirect_to forecast_rainfalls_path(@forecast) }
    format.xml { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rainfall
      @rainfall = Rainfall.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rainfall_params
      params.require(:rainfall).permit(:amount, :forecast_id)
    end
end
  

app/helpers/rainfall_helper.rb
module RainfallHelper
end

app/views/rainfalls/_form.html.erb
<%= form_for([@forecast, @rainfall]) do |f| %>
<% if @rainfall.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@rainfall.errors.count, "error")%>
prohibited this forecast from being saved:</h2>
<ul>
<% @rainfall.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>
<div class="field">
<p>
<%= f.label :amount %><br />
<%= f.text_field :amount %>
</p>
</div>
<div class="actions">
<%= f.submit %>
</div>
<% end %>

app/views/rainfalls/edit.html.erb
<h1>Editing forecast</h1>
<%= render 'form' %>
<%= link_to 'Show', forecast_rainfall_path(@forecast, @rainfall) %> |
<%= link_to 'Back', forecast_rainfalls_path(@forecast) %>

app/views/rainfalls/index.html.erb
<h1>Rainfall forecasts for <%= @forecast.day %> <%= @forecast.date %></h1>

<table>
<tr>
<th>Rainfall Forecast details</th>
</tr>
<% for rainfall in @rainfalls %>
<tr>
<td><%= rainfall.amount %></td>
<% if user_signed_in? %>
    <td><%= link_to 'Show', forecast_rainfall_path(@forecast, rainfall)%></td>
    <td><%= link_to 'Edit', edit_forecast_rainfall_path(@forecast, rainfall)%></td>
    <td><%= link_to 'Destroy', forecast_rainfall_path(@forecast, rainfall), :confirm => 'Are you sure?', :method => :delete %></td>
<% end %>


</tr>
<% end %>
</table>
<br />
<%= link_to 'New Rainfall Forecast', new_forecast_rainfall_path(@forecast) %>
<%= link_to 'Back to Weather Forecast', @forecast %>

app/views/rainfalls/new.html.erb
<h1>New Rainfall Forecast</h1>
<%= render 'form' %>
<%= link_to 'Back', forecast_rainfalls_path(@forecast) %>

app/views/rainfalls/show.html.erb
<h1>Rainfall Forecast for <%= @forecast.date %> </h1>
<p>
<b>Rainfall Amount (mm):</b>
<%= @rainfall.amount %>
</p>
<%= link_to 'Edit', edit_forecast_rainfall_path(@forecast, @rainfall) %> |
<%= link_to 'Back', forecast_rainfalls_path(@forecast) %>