config/routes.rb
Rails.application.routes.draw do
  resources :blogposts do
    resources :comments
  end
  resources :forecasts do
    resources :rainfalls
  end
  resources :profiles
  devise_for :users
  root to: "home#index"
  get 'comments/index', :action=>"index", :controller=>"comments"
  get 'comments/show', :action=>'show', :controller=>'comments'
  get 'comments/new', :action=>'new', :controller=>'comments'
  get 'comments/edit', :action=>'edit', :controller=>'comments'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  #get 'home/index', :controller=>'weekdays', :action=>'day'
  get 'home/index'
  get 'rainfalls/index', :action=>'index', :controller=>'rainfalls'
  #post 'rainfalls/create', :action=>'create', :controller=>'rainfalls'
  get 'rainfalls/show', :action=>'show', :controller=>'rainfalls'
  #get 'rainfalls/show/:id/:forecast_id', :action=>'show', :controller=>'rainfalls'
  get 'rainfalls/new', :action=>'new', :controller=>'rainfalls'
  get 'rainfalls/edit', :action=>'edit', :controller=>'rainfalls'
  #post 'forecasts/:forecast_id/rainfalls/:id', :action=>'create', :controller=>'rainfalls' => as 
  #post '/checkprofanity', :controller=>'comments', :action=>'isprofanity'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #get '/day', :controller=>'weekdays', :action=>'day'
  #post '/day', :controller=>'weekdays', :action=>'day'
  get 'blogpostsearch', to: "blogposts#search"
  get 'forecastsearch', to: "forecasts#search"

end

app/models/forecast.rb
class Forecast < ApplicationRecord
    has_many :rainfall, :dependent => :delete_all
    validates :day , presence: true, length: {minimum: 6, maximum: 9}
    validates :date , presence: true, length: {minimum: 8}
    validates :forecast , presence: true, length: {minimum: 10}
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  #before_action :authenticate_user!
  before_action :ensure_admin, :only => [ :new, :edit, :destroy]
  before_action :set_forecast, only: %i[ show edit update destroy ]

  def ensure_admin
    unless current_user && current_user.admin?
      render :text => "Access Error Message", :status => :unauthorized
    end
  end
  
  # GET /forecasts or /forecasts.json
  def index
    @forecasts = Forecast.all
  end

  def search
    @forecasts = Forecast.where("date::text LIKE ?", "%" + params[:query] + "%")
  end

  # GET /forecasts/1 or /forecasts/1.json
  def show
  end

  # GET /forecasts/new
  def new
    @forecast = Forecast.new
  end

  # GET /forecasts/1/edit
  def edit
  end

  # POST /forecasts or /forecasts.json
  def create
    @forecast = Forecast.new(forecast_params)

    respond_to do |format|
      if @forecast.save
        format.html { redirect_to @forecast, notice: "Forecast was successfully created." }
        format.json { render :show, status: :created, location: @forecast }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @forecast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forecasts/1 or /forecasts/1.json
  def update
    respond_to do |format|
      if @forecast.update(forecast_params)
        format.html { redirect_to @forecast, notice: "Forecast was successfully updated." }
        format.json { render :show, status: :ok, location: @forecast }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @forecast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forecasts/1 or /forecasts/1.json
  def destroy
    @forecast.destroy
    respond_to do |format|
      format.html { redirect_to forecasts_url, notice: "Forecast was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forecast
      @forecast = Forecast.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def forecast_params
      params.require(:forecast).permit(:day, :date, :forecast)
    end
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
end

app/views/forecasts/_forecast_record.erb
<h1>Forecasts</h1>
<% @forecasts.each do |forecast| %>
  <div class="container bg-light border mb-4 justify-content-md-center">
    <div class="row">
      <div class="col">
        <div>
          <h2>Forecast Info</h2>
          <p>
            <strong>Day:</strong>
            <%= forecast.day %>
          </p>

          <p>
            <strong>Date:</strong>
            <%= forecast.date %>
          </p>

          <p>
            <strong>Forecast:</strong>
            <%= forecast.forecast %>
          </p>

          <!-- Display the reviews of a movie -->
          <h2>Rainfall Forecast</h2>
          <% forecast.rainfall.each do |rainfall| %>
          <p>
          <b>Rainfall details:</b>
          <%= rainfall.amount %>
          </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/forecasts/_form.html.erb
<%= form_with(model: forecast) do |form| %>
  <% if forecast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(forecast.errors.count, "error") %> prohibited this forecast from being saved:</h2>

      <ul>
        <% forecast.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :day %>
    <%= form.text_field :day %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :forecast %>
    <%= form.text_field :forecast %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/forecasts/edit.html.erb
<h1>Editing Forecast</h1>

<%= render 'form', forecast: @forecast %>

<%= link_to 'Show', @forecast %> |
<%= link_to 'Back', forecasts_path %>

app/views/forecasts/index.html.erb
<%= render partial: "shared/navbar" %>
<%= render partial: "shared/forecast_search" %>

<div class="row">
  <div class="col text-center justify-content-center pt-5">
    <p id="notice"><%= notice %></p>
  
    <h1>Forecasts</h1>
    <div>
      <table class="table table-responsive">
        <thead>
          <tr>
            <th>Day</th>
            <th>Date</th>
            <th>Forecast</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <div>
          <% @forecasts.each do |forecast| %>
            <tr>
              <td><%= forecast.day %></td>
              <td><%= forecast.date %></td>
              <td><%= forecast.forecast %></td>
              <td><%= link_to 'Show', forecast %></td>
              <% if user_signed_in? && current_user.admin? %>
                <td><%= link_to 'Edit', edit_forecast_path(forecast) %></td>
                <td><%= button_to 'Destroy', forecast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            </tr>                            
          <% end %>
        </div>
      </table>
    </div>
    <br>
    <% if user_signed_in? && current_user.admin? %>
      <%= link_to 'New Forecast', new_forecast_path %>
    <% end %>
  </div>
</div>

app/views/forecasts/new.html.erb
<h1>New Forecast</h1>

<%= render 'form', forecast: @forecast %>

<%= link_to 'Back', forecasts_path %>

app/views/forecasts/search.html.erb
<head>
  <%= render partial: "shared/navbar" %>
</head>

<h1> Searched Forecast Results</h1>

<%= render partial: "forecasts/forecast_record" %>

<% if @forecasts.blank? %>
    <div class="row justify-content-center">
        <div class="col col-lg-12 justify-content-center text-center">
            <h2 class="text-danger pb-5 pt-5">No records for searched forecast date</h2>  
        </div>
    </div>
<% end %>

<footer>
  <%= render partial: "shared/footer" %>
</footer>

app/views/forecasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @forecast.day %>
</p>

<p>
  <strong>Date:</strong>
  <%= @forecast.date %>
</p>

<p>
  <strong>Forecast:</strong>
  <%= @forecast.forecast %>
</p>

<!-- Display the reviews of a movie -->
<h2>Rainfall Forecast</h2>
<% @forecast.rainfall.each do |rainfall| %>
<p>
<b>Rainfall details:</b>
<%= rainfall.amount %>
</p>
<% end %>
<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'Edit Forecast', edit_forecast_path(@forecast) %> |
  <%= link_to 'Forecast Rainfall', forecast_rainfalls_path(@forecast) %>
<% end %>
<%= link_to 'Back', forecasts_path %>